# Generated by Django 3.2.8 on 2021-11-13 21:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchOffices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffices',
            name='description',
            field=ckeditor.fields.RichTextField(default='2'),
            preserve_default=False,
        ),
    ]
