# Generated by Django 3.2.8 on 2021-12-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchOffices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchoffices',
            name='specialty',
        ),
    ]
