# Generated by Django 3.2.8 on 2021-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchOffices', '0002_branchoffices_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffices',
            name='description',
            field=models.TextField(),
        ),
    ]
