# Generated by Django 3.2.8 on 2021-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('branchOffices', '0002_remove_branchoffices_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffices',
            name='specialty',
            field=models.ManyToManyField(to='doctors.Specialty'),
        ),
    ]
