# Generated by Django 3.2.8 on 2022-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchOffices', '0003_branchoffices_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branchOffices', verbose_name='Imagen'),
        ),
    ]
