# Generated by Django 3.2.8 on 2021-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sick',
            field=models.BooleanField(default=False),
        ),
    ]
