# Generated by Django 3.2.8 on 2021-11-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='exam',
        ),
    ]
