# Generated by Django 3.2.8 on 2021-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('usersApp', '0002_usuario_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='Doctor', to='doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='exam',
            field=models.ManyToManyField(blank=True, null=True, related_name='Examen', to='doctors.Exam'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='patology',
            field=models.ManyToManyField(blank=True, null=True, related_name='Patologia', to='doctors.Patology'),
        ),
    ]
