# Generated by Django 3.2.8 on 2021-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_usuario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nrMembership',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
