# Generated by Django 3.2.8 on 2021-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, default='perfil/undefined.jpg', null=True, upload_to='perfil/', verbose_name='image de perfil'),
        ),
    ]
