# Generated by Django 3.2.8 on 2022-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0006_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, default='perfil/undefined.jpg', null=True, upload_to='perfil', verbose_name='image de perfil/'),
        ),
    ]
