# Generated by Django 3.2.8 on 2021-11-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simbolic',
        ),
    ]
