# Generated by Django 3.2.8 on 2021-11-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
