# Generated by Django 3.2.8 on 2021-11-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_exam_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='descripption',
            new_name='description',
        ),
    ]
