# Generated by Django 3.2.8 on 2021-11-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_specialty_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='specialty',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
