# Generated by Django 3.2.8 on 2021-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_rename_descripption_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='asigned',
            field=models.BooleanField(default=False, verbose_name='Asignado'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='result',
            field=models.BooleanField(default=False, verbose_name='Realizado'),
        ),
    ]
