# Generated by Django 3.2.8 on 2021-11-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20211122_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
